name: Profile Views — Live Data

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests plotly kaleido

      - name: Update live data & thumbnail
        run: python scripts/update_views_live.py

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/data/views.json docs/thumbnail.png README.md
          git commit -m "chore: update live profile views" || echo "No changes"
          git push
        env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
